<?php

namespace Boctulus\Simplerest\Controllers\Api;

use Boctulus\Simplerest\Core\Api\ApiController; 

class Webhooks extends ApiController
{ 
    static protected $hidden = ['secret'];
    static protected $hide_in_response = true;
    static protected $soft_delete = true;

    function __construct()
    {       
        parent::__construct();
    }

    public function patch($id = null, $action = null)
    {
        if ($action === null) {
            parent::patch($id);
            return;
        }

        if ($action !== 'rotate_secret' || $id === null) {
            error('Unknown webhook action', 404);
            return;
        }

        return $this->rotateSecret($id);
    }

    protected function onPostingBeforeCheck($id, array &$data)
    {
        if (array_key_exists('secret', $data)) {
            error('Webhook secret is generated by the server; use the rotate_secret action to replace it.', 400);
            return;
        }

        $data['secret'] = $this->generateDeliverySecret();
    }

    protected function onPuttingBeforeCheck($id, array &$data)
    {
        if (array_key_exists('secret', $data)) {
            error('Webhook secret cannot be changed through CRUD; use the rotate_secret action.', 400);
        }
    }

    protected function webhook(string $op, $data, $id = null)
    {
        if (is_array($data)) {
            $data = $this->withoutSecrets($data);
        }

        parent::webhook($op, $data, $id);
    }

    protected function withoutSecrets(array $data): array
    {
        unset($data['secret']);

        foreach ($data as $key => $value) {
            if (is_array($value)) {
                $data[$key] = $this->withoutSecrets($value);
            }
        }

        return $data;
    }

    protected function generateDeliverySecret(): string
    {
        return bin2hex(random_bytes(32));
    }

    protected function rotateSecret($id)
    {
        if (!ctype_digit((string) $id)) {
            error('Invalid webhook id', 400);
            return;
        }

        $instance = $this->getModelInstance();
        $instance->connect();

        $idField = $instance->getIdName();
        $ownerField = $instance->belongsTo();
        $fields = [$idField];
        if ($instance->inSchema([$ownerField])) {
            $fields[] = $ownerField;
        }

        $row = $instance->where([$idField => $id])->first($fields);
        if (empty($row)) {
            error('Webhook subscription not found', 404);
            return;
        }

        $acl = acl();
        if (
            $instance->inSchema([$ownerField])
            && !$acl->hasSpecialPermission('write_all')
            && (string) $row[$ownerField] !== (string) auth()->uid()
        ) {
            error('Forbidden', 403, 'You are not the owner.');
            return;
        }

        try {
            $secret = $this->generateDeliverySecret();
            $updatedBy = $instance->updatedBy();
            $fillable = ['secret'];
            $changes = ['secret' => $secret];

            if ($instance->inSchema([$updatedBy])) {
                $fillable[] = $updatedBy;
                $changes[$updatedBy] = auth()->uid();
            }

            $instance->fill($fillable);
            $updated = $instance->where([$idField => $id])->update($changes);
            if ($updated === false || (int) $updated < 1) {
                error('Webhook secret rotation failed', 500);
                return;
            }
        } catch (\Throwable $e) {
            error('Webhook secret rotation failed', 500);
            return;
        }

        response()->send([
            $idField => $id,
            'secret' => $secret
        ]);
    }
}
