<?php

namespace Boctulus\Simplerest\Core\Libs;

use Boctulus\Simplerest\Core\Libs\Strings;

class MockNames
{
    protected $spanish_names = [
        "Alejandro",
        "María",
        "Juan",
        "Sofía",
        "Carlos",
        "Lucía",
        "José",
        "Camila",
        "Fernando",
        "Gabriela",
        "Miguel",
        "Valeria",
        "Antonio",
        "Isabella",
        "Pedro",
        "Victoria",
        "Francisco",
        "Martina",
        "Ricardo",
        "Andrea",
        "Jorge",
        "Daniela",
        "Rafael",
        "Natalia",
        "Manuel",
        "Elena",
        "Diego",
        "Paula",
        "Luis",
        "Laura",
        "Raúl",
        "Julia",
        "Pablo",
        "Claudia",
        "Santiago",
        "Alejandra",
        "Mario",
        "Lorena",
        "Sebastián",
        "Patricia",
        "Ángel",
        "Carla",
        "David",
        "Mariana",
        "Javier",
        "Mónica",
        "Iván",
        "Luz",
        "Adrián",
        "Ana",
        "Samuel",
        "Verónica",
        // Compuestos:
        "Juan Pablo",
        "Ana María",
        "Luis Fernando",
        "María José",
        "José Antonio",
        "Carlos Alberto",
        "María Fernanda",
        "Miguel Ángel",
        "Juan Carlos",
        "Ana Sofía",
        "José Luis",
        "María Elena",
        "José Manuel",
        "Juan José",
        "María Isabel",
        "Luis Alberto",
        "María Teresa",
        "José Miguel",
        "Ana Paula",
        "Juan Manuel"
    ];    

    protected $spanish_lastnames = [
        "García",
        "Rodríguez",
        "Martínez",
        "López",
        "Sánchez",
        "Pérez",
        "González",
        "Hernández",
        "Torres",
        "Ramírez",
        "Flores",
        "Rivera",
        "Gómez",
        "Díaz",
        "Vázquez",
        "Castillo",
        "Ortiz",
        "Morales",
        "Gutiérrez",
        "Jiménez",
        "Ramos",
        "Fernández",
        "Ruiz",
        "Chávez",
        "Mendoza",
        "Cruz",
        "Reyes",
        "Aguilar",
        "Romero",
        "Vargas",
        "Castro",
        "Suárez",
        "Domínguez",
        "Santos",
        "Medina",
        "Iglesias",
        "Delgado",
        "Paredes",
        "Alonso",
        "Cabrera",
        "Montoya",
        "Campos",
        "Silva",
        "Peña",
        "Mora",
        "Escobar",
        "Núñez",
        "Miranda",
        "Velázquez",
        "Rivas",
        "Moreno",
        "León",
        "Navarro",
        "Espinoza",
        "Cortés",
        "Carrillo",
        "Blanco",
        "Barrios",
        "Benítez",
        "Fuentes",
        "Arias",
        "Vera",
        "Rojas",
        "Figueroa",
        "Acosta",
        "Luna",
        "Salinas",
        "Bravo",
        "Correa",
        "Márquez",
        "Sierra",
        "Valencia",
        "Cano",
        "Maldonado",
        "Vega",
        "Herrera",
        "Ponce",
        "Ortega",
        "Guerrero",
        "Sosa",
        "Mejía",
        "Rosales",
        "Zamora",
        "Lara",
        "Escudero",
        "Carmona",
        "Padilla",
        "Bautista",
        "Valdez",
        "Carrasco",
        "Moya",
        "Gallegos",
        "Palacios",
        "Barrera",
        "Olivares",
        "Álvarez",
        "Roldán",
        "Serna",
        "Muñoz",
        "Salazar",
        "Pizarro",
        "Del Río",
        "Andrade",
        "Arroyo"
    ];

    function getSpanishFirstName(){
        return $this->spanish_names[array_rand($this->spanish_names)];
    }

    function getSpanishLastName(){
        return $this->spanish_lastnames[array_rand($this->spanish_lastnames)];
    }

    function getSpanishFullName(){
        return $this->getSpanishFirstName() . ' ' . $this->getSpanishLastName();
    }
}
