<?php

return [
    "Alice", "Alessia", "Agnese", "Arianna", "Beatrice",
    "Bianca", "Caterina", "Chiara", "Claudia", "Cristina",
    "Diana", "Elena", "Elisa", "Emma", "Federica",
    "Francesca", "Gabriella", "Giorgia", "Giulia", "Ilaria",
    "Isabella", "Laura", "Lavinia", "Livia", "Lucrezia",
    "Marta", "Martina", "Matilde", "Michela", "Natalia",
    "Nicole", "Olivia", "Patrizia", "Raffaella", "Roberta",
    "Sara", "Silvia", "Simona", "Sofia", "Valentina",
    "Vanessa", "Vittoria", "Ylenia", "Zoe",
    "Adriana", "Agata", "Alberta", "Aleandra", "Alexandra",
    "Allegra", "Alma", "Amelia", "Anita", "Anna",
    "Annalisa", "Antonella", "Aurora", "Barbara", "Beatriz",
    "Benedetta", "Bettina", "Biancamaria", "Camilla", "Carla",
    "Carlotta", "Carmela", "Carolina", "Cecilia", "Celeste",
    "Cinzia", "Clara", "Clelia", "Concetta", "Daniela",
    "Debora", "Donatella", "Egle", "Elettra", "Elvira",
    "Emilia", "Ermelinda", "Ester", "Fabiana", "Fabiola",
    "Fedora", "Felicia", "Fernanda", "Filomena", "Flavia",
    "Fortunata", "Francesca", "Gabriela", "Gemma", "Gianina",
    "Gina", "Giovanna", "Graziella", "Guendalina", "Ida",
    "Ildebranda", "Ines", "Ingrid", "Iolanda", "Irene",
    "Irma", "Isidora", "Ivana", "Jolanda", "Laura",
    "Lea", "Leda", "Letizia", "Lia", "Liana",
    "Lidia", "Liliana", "Lina", "Linda", "Livia",
    "Loretta", "Loredana", "Lorenza", "Luana", "Lucia",
    "Ludovica", "Luigia", "Luisa", "Luna", "Maddalena",
    "Mafalda", "Mara", "Marcella", "Margarita", "Margherita",
    "Maria", "Mariangela", "Marianne", "Marina", "Marisa",
    "Marta", "Matilde", "Melania", "Mia", "Michela",
    "Mila", "Mirella", "Miriam", "Monica", "Nadia",
    "Natalia", "Nella", "Nicoletta", "Nina", "Noemi",
    "Olga", "Olimpia", "Ondina", "Oriana", "Ornella",
    "Paola", "Patrizia", "Piera", "Primavera", "Priscilla",
    "Renata", "Rita", "Roberta", "Rosa", "Rosalia",
    "Rosanna", "Rosaria", "Rosella", "Rovena", "Sabina",
    "Sabrina", "Salvina", "Sandra", "Santa", "Sara",
    "Selena", "Serena", "Silvana", "Silvia", "Simonetta",
    "Sofia", "Sonia", "Stella", "Susanna", "Teresa",
    "Tina", "Tommasa", "Umberta", "Valentina", "Valeria",
    "Vanda", "Vanessa", "Velia", "Vera", "Veronica",
    "Vincenza", "Viola", "Virginia", "Vittoria", "Viviana",
    "Zita"
];