<?php

return array(
    "Alessandro", "Giuseppe", "Francesco", "Mario", "Leonardo", "Luca", "Lorenzo", "Matteo", "Giovanni", "Antonio",
    "Roberto", "Marco", "Andrea", "Davide", "Angelo", "Stefano", "Michele", "Fabio", "Vincenzo", "Paolo",
    "Alberto", "Diego", "Simone", "Davide", "Emanuele", "Alessio", "Tommaso", "Christian", "Riccardo", "Filippo",
    "Federico", "Daniele", "Luca", "Enrico", "Gennaro", "Salvatore", "Emilio", "Marcello", "Claudio", "Sergio",
    "Piero", "Angelo", "Giorgio", "Massimiliano", "Gino", "Pietro", "Giampaolo", "Umberto", "Domenico", "Raffaele",
    "Fabrizio", "Alessandro", "Giorgio", "Giovanni", "Luigi", "Mauro", "Alberto", "Luigi", "Stefano", "Paolo",
    "Francesco", "Andrea", "Roberto", "Marco", "Luca", "Davide", "Simone", "Lorenzo", "Federico", "Matteo",
    "Alessio", "Giovanni", "Antonio", "Angelo", "Riccardo", "Diego", "Enrico", "Vincenzo", "Christian", "Emanuele",
    "Fabio", "Filippo", "Michele", "Tommaso", "Giuseppe", "Daniele", "Davide", "Mario", "Alessandro", "Luca",
    "Leonardo", "Francesco", "Lorenzo", "Giorgio", "Simone", "Marco", "Alberto", "Paolo", "Stefano", "Federico",
    "Alessio", "Roberto", "Angelo", "Davide", "Giovanni", "Antonio", "Vincenzo", "Matteo", "Christian", "Riccardo",
    "Fabio", "Michele", "Emanuele", "Tommaso", "Diego", "Daniele", "Enrico", "Simone", "Alessandro", "Mario",
    "Francesco", "Leonardo", "Luca", "Lorenzo", "Marco", "Giovanni", "Roberto", "Matteo", "Angelo", "Andrea",
    "Stefano", "Antonio", "Davide", "Alessio", "Michele", "Vincenzo", "Federico", "Paolo", "Christian", "Giuseppe",
    "Fabio", "Diego", "Emanuele", "Simone", "Riccardo", "Alberto", "Giorgio", "Domenico", "Pietro", "Massimiliano",
    "Claudio", "Gino", "Mauro", "Sergio", "Angelo", "Piero", "Giampaolo", "Umberto", "Raffaele", "Fabrizio",
    "Alessandro", "Giorgio", "Giovanni", "Luigi", "Mauro", "Alberto", "Stefano", "Paolo", "Francesco", "Andrea",
    "Roberto", "Marco", "Luca", "Davide", "Simone", "Lorenzo", "Federico", "Matteo", "Alessio", "Giovanni",
    "Antonio", "Angelo", "Riccardo", "Diego", "Enrico", "Vincenzo", "Christian", "Emanuele", "Fabio", "Filippo",
    "Michele", "Tommaso", "Giuseppe", "Daniele", "Davide", "Mario", "Alessandro", "Luca", "Leonardo", "Francesco",
    "Gabriele", "Giacomo", "Giancarlo", "Gianfranco", "Gianluca", "Gianmarco", "Gianpaolo", "Gianpiero", "Gianluigi", "Gioele",
    "Gioacchino", "Giordano", "Giorgio", "Giovanni", "Giuliano", "Giulio", "Giuseppe", "Gregorio", "Guido",
    "Ilario", "Italo", "Ivan", "Ivo",
    "Jacopo", "Jovanotti",
    "Leandro", "Leonardo", "Lino", "Lorenzo", "Luca", "Luciano", "Lucio", "Luigi", "Luis", "Lorenzo", "Loris", "Lino",
    "Marco", "Massimiliano", "Matteo", "Mauro", "Mario", "Mattia", "Matteo", "Michele", "Mirko",
    "Nathan", "Nello", "Neri",
    "Omar", "Oreste", "Orlando", "Ottavio", "Ottone",
    "Paolo", "Patrizio", "Pietro", "Primo",
    "Raffaele", "Raimondo", "Raul", "Renato", "Riccardo", "Roberto", "Rolando", "Romano", "Romeo", "Ruggero",
    "Salvatore", "Samuele", "Sandro", "Sante", "Saverio", "Sebastiano", "Sergio", "Silvano", "Silvio", "Simone", "Stefano",
    "Tommaso", "Tony", "Tullio",
    "Ugo", "Umberto", "Urbano",
    "Valentino", "Vanni", "Vasco", "Venceslao", "Vincenzo", "Vinicio", "Virgilio", "Vittorino", "Vittorio",
    "Walter", "Willy", "Wladimiro",
    "Xavier", "Xeno",
    "Yuri",
    "Zeno", "Zenone", "Zaccaria", "Zefirino", "Zeffiro", "Zelindo", "Zeno", "Zenone", "Zoran"
);
