<?php

namespace simplerest\controllers;

use simplerest\controllers\MyController;
use simplerest\core\Request;
use simplerest\core\Response;
use simplerest\core\libs\Factory;
use simplerest\core\libs\DB;

class StripHtmlController extends MyController
{
    function test()
    {   
        $html = <<<'HTML'
                <table class="xdebug-error xe-warning" dir="ltr" border="1" cellspacing="0" cellpadding="1">
        <tbody><tr><th align="left" bgcolor="#f57900" colspan="5" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #d26500;"><span style="background-color: rgb(204, 0, 0); color: rgb(252, 233, 79); font-size: x-large; --darkreader-inline-bgcolor: #ad0000; --darkreader-inline-color: #fffb54;" data-darkreader-inline-bgcolor="" data-darkreader-inline-color="">( ! )</span> Warning: fopen(D:\www\lms1/wp-content/uploads/learndash/add-ons/learndash-add-ons.pid): failed to open stream: Permission denied in D:\www\lms1\wp-content\plugins\sfwd-lms\includes\class-ld-bitbucket-api.php on line <i>392</i></th></tr>
        <tr><th align="left" bgcolor="#e9b96e" colspan="5" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #8a5b10;">Call Stack</th></tr>
        <tr><th align="center" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">#</th><th align="left" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">Time</th><th align="left" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">Memory</th><th align="left" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">Function</th><th align="left" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">Location</th></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">0.0002</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">368000</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">{main}(  )</td><td title="D:\www\lms1\wp-admin\post.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\post.php<b>:</b>0</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">2</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">0.5706</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">19558296</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">require( <font color="#00bb00" data-darkreader-inline-color="" style="--darkreader-inline-color: #4aff4a;">'D:\www\lms1\wp-admin\edit-form-blocks.php</font> )</td><td title="D:\www\lms1\wp-admin\post.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\post.php<b>:</b>187</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">3</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.4194</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">27897896</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">require_once( <font color="#00bb00" data-darkreader-inline-color="" style="--darkreader-inline-color: #4aff4a;">'D:\www\lms1\wp-admin\admin-header.php</font> )</td><td title="D:\www\lms1\wp-admin\edit-form-blocks.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\edit-form-blocks.php<b>:</b>309</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">4</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5745</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28348408</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">do_action( <span>$hook_name = </span><span>'admin_notices'</span> )</td><td title="D:\www\lms1\wp-admin\admin-header.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\admin-header.php<b>:</b>303</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">5</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5745</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28348784</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">WP_Hook-&gt;do_action( <span>$args = </span><span>[0 =&gt; '']</span> )</td><td title="D:\www\lms1\wp-includes\plugin.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\plugin.php<b>:</b>517</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">6</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5745</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28348784</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">WP_Hook-&gt;apply_filters( <span>$value = </span><span>''</span>, <span>$args = </span><span>[0 =&gt; '']</span> )</td><td title="D:\www\lms1\wp-includes\class-wp-hook.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\class-wp-hook.php<b>:</b>334</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">7</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5773</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28346752</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">nss_plugin_updater_sfwd_lms-&gt;admin_notice_upgrade_notice( <span>''</span> )</td><td title="D:\www\lms1\wp-includes\class-wp-hook.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\class-wp-hook.php<b>:</b>310</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">8</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5773</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28347160</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">nss_plugin_updater_sfwd_lms-&gt;get_plugin_upgrade_notice( <span>$admin = </span><span>'upgrade_notice_admin'</span> )</td><td title="D:\www\lms1\wp-content\plugins\sfwd-lms\includes\ld-autoupdate.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\ld-autoupdate.php<b>:</b>328</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">9</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5773</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28347160</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">nss_plugin_updater_sfwd_lms-&gt;get_plugin_readme(  )</td><td title="D:\www\lms1\wp-content\plugins\sfwd-lms\includes\ld-autoupdate.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\ld-autoupdate.php<b>:</b>475</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">10</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5773</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28347160</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">LearnDash_Addon_Updater-&gt;get_addon_plugins( <span>$override_cache = </span><span>FALSE</span> )</td><td title="D:\www\lms1\wp-content\plugins\sfwd-lms\includes\ld-autoupdate.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\ld-autoupdate.php<b>:</b>461</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">11</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5773</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28347160</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">LearnDash_BitBucket_API-&gt;get_bitbucket_repositories( <span>$override_cache = </span><span>FALSE</span> )</td><td title="D:\www\lms1\wp-content\plugins\sfwd-lms\includes\class-ld-addons-updater.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\class-ld-addons-updater.php<b>:</b>571</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">12</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5776</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28347240</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">LearnDash_BitBucket_API-&gt;lock_bitbucket_repository( <span>$plugin_key = </span><span>'learndash-add-ons'</span> )</td><td title="D:\www\lms1\wp-content\plugins\sfwd-lms\includes\class-ld-bitbucket-api.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\class-ld-bitbucket-api.php<b>:</b>240</td></tr>
        <tr><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">13</td><td bgcolor="#eeeeec" align="center" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">1.5776</td><td bgcolor="#eeeeec" align="right" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">28347336</td><td bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;"><a href="http://www.php.net/function.fopen" target="_new">fopen</a>( <span>$filename = </span><span>'D:\\www\\lms1/wp-content/uploads/learndash/add-ons/learndash-add-ons.pid'</span>, <span>$mode = </span><span>'w+'</span> )</td><td title="D:\www\lms1\wp-content\plugins\sfwd-lms\includes\class-ld-bitbucket-api.php" bgcolor="#eeeeec" data-darkreader-inline-bgcolor="" style="--darkreader-inline-bgcolor: #1f2224;">...\class-ld-bitbucket-api.php<b>:</b>392</td></tr>
        </tbody></table>
        HTML;

       dd(
        strip_tags($html)
       );
                       
    }
}

